# Project Name
export PROJECT = $(notdir $(PWD))

# List of build core directories. Relative to current directory.
export CORE_DIRS = $(abspath \
../../projects/$(PROJECT)/xil_cores \
../../modules/KpixDaq/xil_cores \
../../modules/eth_client/xil_cores \
../../modules/EvrCore/xil_cores)

include ../../xilinx_common.mk

