# Project Name
export PROJECT = $(notdir $(PWD))

# List of build core directories. Relative to current directory.
export CORE_DIRS = $(abspath \
../../modules/EthClientCore/xil_cores)

include ../../xilinx_common.mk

