#!/usr/bin/env python3
import sys
import os
import argparse

import rogue
import pyrogue
import pyrogue.gui
import pyrogue.interfaces


if '--local' in sys.argv:
    baseDir = os.path.dirname(os.path.realpath(__file__))
    pyrogue.addLibraryPath(f'{baseDir}/../../firmware/common/python')
    pyrogue.addLibraryPath(f'{baseDir}/../../firmware/submodules/surf/python')

import KpixDaq

#rogue.Logging.setFilter('pyrogue.SrpV3', rogue.Logging.Debug)
# Set the argument parser
parser = argparse.ArgumentParser()

parser.add_argument(
    "--host", 
    type     = str,
    required = False,
    default = 'localhost',
    help     = "ZMQ Server host (or ip address)",
)  

parser.add_argument(
    "--port", 
    type     = int,
    required = False,
    default = 9099,
    help     = "ZMQ Server port",
)  


args = parser.parse_known_args()[0]
print(args)

client = pyrogue.interfaces.VirtualClient(addr=args.host, port=args.port)
root = client.root


# Create GUI
appTop = pyrogue.gui.application(sys.argv)
guiTop = pyrogue.gui.GuiTop()
guiTop.addTree(root)
guiTop.resize(1000,1000)

# Run gui
appTop.exec_()

