#!/usr/bin/env python3

import sys
import os
import logging
import argparse
import datetime

import pyrogue
import rogue

if '--local' in sys.argv:
    baseDir = os.path.dirname(os.path.realpath(__file__))
    pyrogue.addLibraryPath(f'{baseDir}/../../firmware/common/python')
    pyrogue.addLibraryPath(f'{baseDir}/../../firmware/submodules/surf/python')

import KpixDaq

#rogue.Logging.setFilter('pyrogue.SrpV3', rogue.Logging.Debug)
rootParser = KpixDaq.DesyTrackerRootArgparser()
runParser = argparse.ArgumentParser()

runParser.add_argument(
    '--config', '-c',
    type = str,
    required = True,
    help = 'Configuration yaml file')

runParser.add_argument(
    '--outfile', '-o',
    type = str,
    required = False,
    default = os.path.abspath(datetime.datetime.now().strftime("data/Calibration_%Y%m%d_%H%M%S.dat")),
    help = 'Output file name')


if __name__ == "__main__":

    rootArgs = rootParser.parse_known_args()[0]
    runArgs = runParser.parse_known_args()[0]

    with KpixDaq.DesyTrackerRoot(**vars(rootArgs)) as root:

        root.ReadAll()
        root.waitOnUpdate()

        root.DesyTracker.AxiVersion.printStatus()

        if os.path.isdir(runArgs.outfile):
            runArgs.outfile = os.path.abspath(datetime.datetime.now().strftime(f"{runArgs.outfile}/Calibration_%Y%m%d_%H%M%S.dat"))

        print(f'Opening data file: {runArgs.outfile}')
        root.DataWriter.DataFile.setDisp(runArgs.outfile)
        root.DataWriter.Open()

        print(f"Hard Reset")
        root.HardReset()

        print(f"Count Reset")
        root.CountReset()

        print('Writing initial configuration')
        root.LoadConfig(runArgs.config)
        root.waitOnUpdate()
        root.ReadAll()
        root.waitOnUpdate()

        try:
            root.DesyTrackerRunControl.runState.setDisp('Calibration')
            root.DesyTrackerRunControl.waitStopped()
            root.DataWriter.Close()
        except (KeyboardInterrupt):
            root.DesyTrackerRunControl.runState.setDisp('Stopped')
            root.DataWriter.Close()
