#!/usr/bin/env python

import sys
import os.path
import time
import pyrogue
import rogue.utilities
import rogue.utilities.fileio

if '--local' in sys.argv:
    baseDir = os.path.dirname(os.path.realpath(__file__))
    pyrogue.addLibraryPath(f'{baseDir}/../../firmware/common/python')
    pyrogue.addLibraryPath(f'{baseDir}/../../firmware/submodules/surf/python')

import KpixDaq

rogue.Logging.setFilter('pyrogue.LegacyStreamReader', rogue.Logging.Debug)

reader = rogue.utilities.fileio.LegacyStreamReader()
#parser = KpixDaq.KpixStreamInfo() #KpixCalibration()
parser = KpixDaq.KpixCalibration()

pyrogue.streamConnect(reader, parser)

def main(args):
    reader.open(args[1])
    print('opened', args[1])
    reader.closeWait()
    print('closed', args[1])
    #parser.process()
    #parser.noise()

if __name__ == "__main__":
    main(sys.argv)
