#!/usr/bin/env python

import sys
import os
import logging
import argparse
import datetime
import time

import pyrogue
import rogue

if '--local' in sys.argv:
    baseDir = os.path.dirname(os.path.realpath(__file__))
    pyrogue.addLibraryPath(f'{baseDir}/../../firmware/common/python')
    pyrogue.addLibraryPath(f'{baseDir}/../../firmware/submodules/surf/python')

import KpixDaq

#rogue.Logging.setFilter('pyrogue.SrpV3', rogue.Logging.Debug)
rogue.Logging.setFilter('pyrogue.ZmqServer', rogue.Logging.Debug)

parser = KpixDaq.DesyTrackerRootArgparser()

if __name__ == "__main__":
    args = parser.parse_known_args()[0]

    with KpixDaq.DesyTrackerRoot(**vars(args)) as root:
        try:
            while True:
                time.sleep(1)
        except (KeyboardInterrupt):
            print('Exiting')
            
        
