# Project Name
export PROJECT = $(notdir $(PWD))

# List of build core directories. Relative to current directory.
CORE_DIRS = xil_cores ../../modules/KpixDaq/xil_cores ../../modules/eth_client/xil_cores

include ../../xilinx_common.mk

